---

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    instance_type: 't2.micro'
    instance_image: 'ami-9062d0f4'
    region: 'ca-central-1'
    aws_zone: 'b'
    keypair: 'primary'
    group_id: 'sg-436cb62a'
  tasks:
  - name: Launch ec2 instance (Application Server)
    local_action: ec2 
                  instance_type={{ instance_type }} 
                  image={{ instance_image }} 
                  keypair={{ keypair }}
                  instance_tags='{"Environment":"DEV","Class":"AppServer","Name":"Application Server"}'
                  region='{{region}}'
                  aws_zone='{{ region }}{{ aws_zone }}'
                  group_id={{ group_id }}
                  wait=true
    register: ec2


#  - name: Add new instance to host group
#    local_action: add_host hostname={{ item.public_ip }} groupname=launched
#    with_items: '{{ ec2.instances }}'

  - name: Wait for instances to listen on port 22
    wait_for:
      state=started
      host={{ item.public_dns_name }}
      port=22
      delay=10
      timeout=300
    with_items: '{{ ec2.instances }}'

