---

- name: install the latest version of git
  yum:
    name: git
    state: latest

- name: deploy devops-halifax webapp
  git:
    repo: https://github.com/mowntan/devops-halifax.git
    dest: /usr/share/nginx/html/devops-halifax/
  tags: deploy

## ANOTHER OPTION
#-  get_url:
#-    url: https://github.com/mowntan/devops-halifax/blob/master/README.md
#-    dest: /usr/share/nginx/html
#-    mode: 0644

